title: Blog Bibliotheks- und Archivinformatik
author: Morena Sager
email: morena.sager@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2024

# social links
github_username:  Sagerin94 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
